### ISSUE TITLE
Getting blank pages / javascript errors when trying to view components and resources that do not have travis configured

### ISSUE THREAD

**Issue by Andy-medidata** [RoadieHQ/backstage-plugin-travis-ci#82]
## Expected Behavior

We have a diverse tech stack, not all repos make use of TravisCI. I would expect that if you do not have Travis configured for a component or resource that the page loads safely, could have the generic "you do not have Travis configured" message in the widget.

## Current Behavior

We're getting blank pages and the following errors showing in dev tools:
![TravisError](https://user-images.githubusercontent.com/44985584/128067480-4c5e339d-69f3-43f3-874f-d31cb036d544.png)

## Possible Solution

uncertain

## Steps to Reproduce

We have version 1.0.8 of the plugin installed.

A Component with the travis tags in the annotations loads fine but all my other Components, Resources, Locations do not. 

a sample Location I was using to test:
`
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Dalton-Location
  description: Location for Dalton components/elements
spec:
  type: url
`

load it and view the page, the error shows up.

## Context

We've had to disable the travis plugin to be able to demo to stakeholders to get approval to continue.

Here is the full list of errors I'm seeing:
[TravisErrors.log](https://github.com/RoadieHQ/backstage-plugin-travis-ci/files/6926373/TravisErrors.log)

## Your Environment

We're running our backstage instance in AWS ECS

- Plugin Version: 1.0.8
- Backstage version (e.g. 0.1.1-alpha23): 0.8.7
- NodeJS Version (e.g. v12):  14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu ???
- Browser Information (e.g. chrome 85): Chrome 92.0.4515.107

**Comment by Xantier** [comment]
Thanks @Andy-medidata, 

We have updated the dependencies of this plugin now to match the latest braking changes from upstream Backstage. The plugins was previously using a different version of the context containing an entity and wouldn't be able to display anything because it couldn't find the correct entity data.

Regarding your issue where some entities contain an annotation to point to travis and some don't you should be able to handle that in your entity page on the code level. 
Backstage example-app does this in the following way:
```
// EntityPage.tsx

const cicdCard = (
   /* snip */
    <EntitySwitch.Case if={isTravisciAvailable}>
      <Grid item sm={6}>
        <EntityTravisCIOverviewCard />
      </Grid>
    </EntitySwitch.Case>
  /* snip */
);
```

I'll close this issue with the above note. Feel free to reopen if you still have problems with this.
